// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Role struct {
	ID       int32
	RoleName string
	RoleNote string
}

type Shop struct {
	ID           string
	ShopName     string
	ShopEmail    string
	ShopPassword string
	IsActive     bool
	Verify       bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ShopRole struct {
	ShopID string
	RoleID int32
}

type Token struct {
	ID               string
	PublicKey        string
	RefreshToken     string
	RefreshTokenUsed sql.NullString
	UserID           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
