// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role.sql

package database

import (
	"context"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (role_name, role_note) VALUES (?, ?)
`

type CreateRoleParams struct {
	RoleName string
	RoleNote string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.RoleName, arg.RoleNote)
	return err
}
