// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: token.sql

package database

import (
	"context"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (id, public_key, refresh_token, user_id) VALUES (?, ?, ?, ?)
`

type CreateTokenParams struct {
	ID           string
	PublicKey    string
	RefreshToken string
	UserID       string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.ID,
		arg.PublicKey,
		arg.RefreshToken,
		arg.UserID,
	)
	return err
}
