// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/phongnd2802/go-backend-api/internal/controllers"
	"github.com/phongnd2802/go-backend-api/internal/repositories"
	"github.com/phongnd2802/go-backend-api/internal/services"
)

// Injectors from wire.access.go:

func InitAccessRouterHandler() (*controllers.AccessController, error) {
	iShopRepository := repositories.NewShopRepository()
	iotpRepository := repositories.NewOTPRepository()
	iTokenRepository := repositories.NewTokenRepository()
	iAccessService := services.NewAccessService(iShopRepository, iotpRepository, iTokenRepository)
	accessController := controllers.NewAccessController(iAccessService)
	return accessController, nil
}
